### ISSUE TITLE
Can't get app context with BPython

### ISSUE THREAD

**Issue by ezequielo** [smurfix/flask-script#155] opened 2016-03-17 11:53 UTC
Seems like when using **BPython** and the flask-script shell, flask-script is not able to get the app context and therefore I need to create it. It's strange because if I uninstall BPython from my virtualenv and install IPython it works perfectly

Have a look to this [stackoverflow question](http://stackoverflow.com/questions/36047585/using-flask-script-shell-with-bpython-cant-get-app-context?)

**Comment by jeffwidman** [comment] 2016-03-21 20:44
FYI--I only have time for basic maintenance mode on this right now (we just had a baby), and the project owner is pretty much absent right now. If you're able to track down the root cause here and submit a PR, I'd be more than happy to review. But otherwise this is unlikely to get fixed in the near future.

**Comment by elvis-macak** [comment] 2016-06-14 10:16
It's not a flask-script bug, should be bpython's bug.

**Comment by elvis-macak** [comment] 2016-06-14 11:13
it's because the bpython also use greenlet, that conflict with the werkzeug's `Local`, so it'll failed to take the start the bpython.

**Closed** 2016-06-14 17:21 UTC

**Comment by elvis-macak** [comment] 2016-06-29 04:56
Seems another import type can fix this problem, 
see pr https://github.com/smurfix/flask-script/pull/165
