### ISSUE TITLE
Using ssl_key & ssl_cert options (instead of ssl_context) throws an error

### ISSUE THREAD

**Issue by philfreo** [smurfix/flask-script#157] opened 2016-04-08 21:32 UTC
According to [the code](https://github.com/smurfix/flask-script/blob/0143ed4390f613d29c2622f1e0ad71ab4918e782/flask_script/commands.py#L374-L376) you should be able to pass `ssl_key` and `ssl_crt` to `Server`, instead of building & passing the `ssl_context` tuple. However because you don't `pop` these from kwargs an error is caused:

```
./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 902, in <module>
    manager.run()
  File "proj/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "proj/venv/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "proj/venv/lib/python2.7/site-packages/flask_script/commands.py", line 425, in __call__
    **self.server_options)
  File "proj/venv/lib/python2.7/site-packages/flask/app.py", line 739, in run
    run_simple(host, port, self, **options)
TypeError: <flask_script.commands.Server object at 0x112a8db50>: run_simple() got an unexpected keyword argument 'ssl_key'
```

tested with Flask 0.9

**Comment by jeffwidman** [comment] 2016-04-09 00:41
Looks like @VladimirPal introduced this in https://github.com/smurfix/flask-script/pull/138/commits/c6604ebb2274d0608789afc95346c5b115ecec06 which I merged in https://github.com/smurfix/flask-script/pull/138

@VladimirPal do you mind fixing?

**Comment by jeffwidman** [comment] 2016-08-04 13:59
Bump @VladimirPal

**Comment by jeffwidman** [comment] 2016-08-04 15:10
@philfreo would you be up for submitting a PR fixing this? 

I'd like to cut a new release soon, and be nice to have this fixed. Afraid I don't have time though to fix this issue (I barely have time to get a release out unfortunately).

**Comment by idangoldman** [comment] 2017-01-14 13:13
@jeffwidman, @philfreo have one of you fixed this thing?

**Comment by philfreo** [comment] 2017-01-14 13:17
Nope, I started using gunicorn instead of runserver.

**Comment by anthraxx** [comment] 2017-09-14 10:36
@philfreo any chance you have a test, as i can't reproduce this with latest flask.

```
> cat test_manager.py
#!/usr/bin/env python
from flask_script import Manager, Server

from app import app

manager = Manager(app)
manager.add_command("runserver", Server(host="::",
                                        port="1234",
                                        ssl_crt="cert.pem", ssl_key="key.pem"))

if __name__ == "__main__":
    manager.run()
```

```
> ./test_manager.py runserver
Enter PEM pass phrase:
 * Running on https://[::]:1234/ (Press CTRL+C to quit)
```

**Comment by philfreo** [comment] 2017-09-14 15:25
Nope, I'm not using this anymore. I was using Flask 0.9 when I opened this.

**Comment by anthraxx** [comment] 2017-09-15 15:37
@jeffwidman any ideas on this? For me everything is working as it should

**Comment by jeffwidman** [comment] 2017-09-16 03:42
No, I had closed as a "can't repro", then thought better of it as I hadn't taken the time to play with it. If you tried and it's all working as expected then let's close it.

**Closed by jeffwidman** 2017-09-16 03:42 UTC
